SOCIAL_AUTH_TWITTER_KEY = 'BVBOWynKxDOQkVLkVMUvxPXzY'
SOCIAL_AUTH_TWITTER_SECRET = 'A2iD5qZSGn3O0qiI3SbVd3nR7LQeHV5n4ikBQDMI7xZxf0ym8D'



SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/home/'
SOCIAL_AUTH_LOGIN_URL = '/'